# Generated by Django 6.0.3 on 2026-03-26 19:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Alimentos',
            fields=[
                ('idalimentos', models.AutoField(db_column='idAlimentos', primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'verbose_name_plural': 'Alimentos',
                'db_table': 'alimentos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AlimentosPlatos',
            fields=[
                ('id_alimentosplatos', models.AutoField(db_column='id_alimentosPlatos', primary_key=True, serialize=False)),
                ('cantidad_utilizada', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'verbose_name_plural': 'Alimentos Platos',
                'db_table': 'alimentos_platos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id_cliente', models.AutoField(primary_key=True, serialize=False)),
                ('puntos_acumulados', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Clientes',
                'db_table': 'cliente',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Domicilios',
            fields=[
                ('id_domicilios', models.AutoField(primary_key=True, serialize=False)),
                ('direccion', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Domicilios',
                'db_table': 'domicilios',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Empleados',
            fields=[
                ('id_empleados', models.AutoField(primary_key=True, serialize=False)),
                ('salario_mensual', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
            options={
                'verbose_name_plural': 'Empleados',
                'db_table': 'empleados',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Estadopedido',
            fields=[
                ('idestadopedido', models.AutoField(db_column='idEstadoPedido', primary_key=True, serialize=False)),
                ('estado', models.CharField(max_length=25)),
            ],
            options={
                'verbose_name_plural': 'Estado Pedidos',
                'db_table': 'estadopedido',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ItemPedido',
            fields=[
                ('id_item', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'verbose_name_plural': 'Items de Pedidos',
                'db_table': 'items_pedidos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id_pedido', models.AutoField(primary_key=True, serialize=False)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('confirmado', 'Confirmado'), ('preparando', 'Preparando'), ('listo', 'Listo'), ('cancelado', 'Cancelado')], default='pendiente', max_length=20)),
                ('fecha_pedido', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
            options={
                'verbose_name_plural': 'Pedidos',
                'db_table': 'pedidos_usuario',
                'ordering': ['-fecha_pedido'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Pedidos',
            fields=[
                ('id_pedido', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField(db_column='Fecha')),
            ],
            options={
                'verbose_name_plural': 'Pedidos',
                'db_table': 'pedidos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('tipodedocumento_id', models.IntegerField(blank=True, db_column='TipoDeDocumento_id', null=True)),
                ('numerodocumento', models.CharField(db_column='NumeroDocumento', max_length=10, unique=True)),
                ('primernombre', models.CharField(db_column='PrimerNombre', max_length=25)),
                ('segundonombre', models.CharField(blank=True, db_column='SegundoNombre', max_length=25, null=True)),
                ('primerapellido', models.CharField(db_column='PrimerApellido', max_length=25)),
                ('segundoapellido', models.CharField(blank=True, db_column='SegundoApellido', max_length=25, null=True)),
                ('fechadenacimiento', models.CharField(blank=True, db_column='FechaDeNacimiento', max_length=25, null=True)),
                ('correo', models.CharField(blank=True, db_column='Correo', max_length=70, null=True)),
                ('telefono', models.CharField(blank=True, db_column='Telefono', max_length=15, null=True)),
                ('id_persona', models.IntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name_plural': 'Personas',
                'db_table': 'persona',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Platos',
            fields=[
                ('id_plato', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=40)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'verbose_name_plural': 'Platos',
                'db_table': 'platos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PlatosPedidos',
            fields=[
                ('id_platos_pedidos', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField()),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'verbose_name_plural': 'Platos Pedidos',
                'db_table': 'platos_pedidos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tiposdedocumentos',
            fields=[
                ('tiposdedocumentos_id', models.AutoField(db_column='TiposDeDocumentos_id', primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=25)),
            ],
            options={
                'verbose_name_plural': 'Tipos de Documentos',
                'db_table': 'tiposdedocumentos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PerfilUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(choices=[('admin', 'Administrador'), ('cliente', 'Cliente')], default='cliente', max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Perfiles de Usuarios',
            },
        ),
    ]
