# Generated by Django 6.0.3 on 2026-04-20 02:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='itempedido',
            options={'verbose_name_plural': 'Items de Pedidos'},
        ),
        migrations.AlterModelOptions(
            name='pedido',
            options={'ordering': ['-fecha_pedido'], 'verbose_name_plural': 'Pedidos'},
        ),
    ]
